import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  main: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    padding: 20,
  },

  map: {
    width: "100%",
    height: "100%",
  },
  button: {
    position: "absolute",
    bottom: 70,
    right: 40,
    backgroundColor: "white",
    padding: 10,
    borderRadius: 100,
  },
  slideUpContainer: {
    height: "60%",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "top",
    borderRadius: 40,
    padding: 20,
  },
  slideUpHeader: {
    position: "relative",
    width: "15%",
    height: 4,
    top: 20,
    left: "42.5%",
    backgroundColor: "#D9D9D9",
    zIndex: 1,
    borderRadius: 20,
  },

  searchBarContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "5%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  searchBar: {
    width: "90%",
    height: "120%",
    backgroundColor: "white",
    borderRadius: 20,
    marginTop: "40%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  searchBarInput: {
    flex: 1,
    width: "80%",
    height: "100%",
    backgroundColor: "white",
    borderRadius: 20,
  },

  restaurant: {
    flex: 1,
    flexDirection: "column",
    paddingHorizontal: 35,
  },
  restaurantTop: {
    flex: 1,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  restaurantImage: {
    backgroundColor: "transparent",
  },
  restaurantInfo: {
    flex: 1,
    marginLeft: 10,
    justifyContent: "top",
    alignContent: "center",
    flexDirection: "column",
  },
  orderAdd2: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: "bold",
    color: "#494949",
  },
  orderAdd1: {
    fontSize: 13,
    color: "#727171",
  },
  roadViewButton: {
    backgroundColor: "#FF9B3F",
    width: 80,
    height: 30,
    borderRadius: 10,
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  roadViewButtonText: {
    fontSize: 12,
    color: "white",
  },
  restaurantBody: {
    flex: 2.5,
    backgroundColor: "#F0F0F0",
    borderRadius: 20,
    marginTop: 20,
    justifyContent: "top",
    alignItems: "center",
    paddingTop: 20,
  },
  restaurantName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#727171",
    marginBottom: 5,
  },
  restaurantAddress: {
    fontSize: 16,
    color: "gray",
  },

  dishCount: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    height: "100%",
  },

  dishCountText: {
    fontSize: 12,
    textAlign: "center",
    fontWeight: "200",
    marginTop: "auto",
  },

  restaurantBottom: {
    marginTop: 20,
    flex: 0.7,
    backgroundColor: "transparent",
  },
  commentText: {
    fontSize: 16,
    color: "#727171",
    textAlign: "center",
  },
  weightText: {
    fontSize: 16,
    color: "#727171",
    textAlign: "center",
  },

  restaurantBottomButton: {
    flex: 1,
    backgroundColor: "#FF9B3F",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.15, // Adjust the shadow opacity as needed
    shadowRadius: 8,
  },

  restaurantButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },

  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
    backgroundColor: "rgba(0,0,0,0.5)",
  },

  modalView: {
    width: "95%",
    height: 334,
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingTop: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#727171",
  },
  modalName: {
    fontSize: 18,
    color: "#727171",
    fontWeight: "500",
    marginTop: 20,
  },
  modalAddressBox: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    width: "100%",
  },
  modalAddress: {
    fontSize: 16,
    color: "gray",
    fontWeight: "500",
    marginTop: 10,
    transform: [{ translateY: -5 }],
  },
  packageContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  packageIcon: {
    marginTop: 20,
  },
  packageShadow: { position: "absolute", top: "50%", left: "-4%" },
  modalButtonContainer: {
    flex: 1,
    flexDirection: "row",
    marginTop: 10,
  },
  modalPickUpButton: {
    flex: 1,
    height: 50,
    backgroundColor: "#FF9B3F",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginHorizontal: 5,
  },
  modalPickUpButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },
  modalExitButton: {
    position: "absolute",
    top: "33%",
    right: 30,
    backgroundColor: "#D9D9D9",
    borderRadius: 100,
    padding: 7,
  },

  pickingupContainer: {
    flex: 1,
    justifyContent: "top",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 40,
    padding: 20,
    height: "40%",
    width: "100%",
    flexDirection: "column",
  },
  pickingupTop: {
    flex: 1,
    width: "100%",
    flexDirection: "row",
    marginTop: 30,
    alignItems: "start",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  restaurantIconHolder: {
    flex: 1,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  restaurantIcon: {
    width: 50,
    height: 50,
  },
  pickUpName: {
    fontSize: 18,
    color: "#494949",
    fontWeight: "700",
    marginBottom: 7,
    marginTop: 13,
  },
  pickUpAddresss: {
    flexDirection: "row",
    justifyContent: "top",
    alignItems: "start",
    marginTop: 5,
  },
  pickUpAddresssText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#727171",
  },
  pickUpButtonHolder: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pickingupBody: {
    flex: 2,
    backgroundColor: "#F0F0F0",
    borderRadius: 20,
    marginTop: 20,
    justifyContent: "top",
    alignItems: "center",
  },

  locationContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "start",
    backgroundColor: "white",
    flexDirection: "column",
    height: "50%",
    paddingHorizontal: 25,
    paddingTop: 10,
    borderRadius: 40,
  },
  locationTop: {
    flex: 0.1,
    width: "100%",
    flexDirection: "column",
    marginTop: 30,
    alignItems: "start",
    justifyContent: "flex-start",
  },
  locationTitle: {
    fontSize: 18,
    color: "#494949",
    fontWeight: "800",
  },
  locationAddressHolder: {
    flex: 1,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "transparent",
  },
  locationAddressText: {
    color: "#727171",
  },
  locationAddress: {
    fontSize: 16,
    color: "#727171",
    fontWeight: "500",
    marginBottom: 7,
  },
  locationBottom: {
    flex: 1,
    marginTop: 30,
  },
  locationBottomScroll: {
    zIndex: 1,
    width: "100%",
  },
  nearPickTitle: {
    fontSize: 18,
    color: "#494949",
    fontWeight: "800",
    marginTop: 10,
  },
  nearPickStyles: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    backgroundColor: "#F0F0F0",
    borderRadius: 20,
    height: 150,
    marginHorizontal: 4,
    width: 180,
    height: 200,
  },
  nearPickImage: {
    backgroundColor: "transparent",
    marginBottom: 8,
  },
  nearPickText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#727171",
    marginBottom: 8,
    height: 44,
  },
  nearPickDistanceText: {
    fontSize: 14,
    color: "#727171",
  },
  nearPickWeight: {
    backgroundColor: "#FE8306",
    borderRadius: 10,
    marginTop: 30,
    padding: 5,
    paddingHorizontal: 15,
    marginRight: "auto",
  },
  nearPickWeightText: {
    fontSize: 16,
    color: "white",
  },

  returnAlertContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FF9B3F",
    borderRadius: 15,
    position: "absolute",
    bottom: "22%",
    left: "5%",
    width: "90%",
    height: "8%",
    //0px 4px 8px 4px rgba(0, 0, 0, 0.15);
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15, // Adjust the shadow opacity as needed
  },
  returnAlertText: {
    fontSize: 16,
    fontWeight: "600",
    color: "white",
  },
});
